### ISSUE TITLE
fix unit testing for brand new forked repos

### ISSUE THREAD

**Issue by llealgt** [OpenMined/PySyft#1520]
The unit tests are failing after just forking the repo even after 0 modifications to the code, i found the issue following this steps(on MacOS using Anaconda):

1. Fork Repo
2. Clone repo to your computer
3. Create conda environment and install requirements from requirements.txt
4. Fix any dependencies and version issues
5. runt tests: python3 setup.py test

Some of the errors in result:
test_tensor2unregsitered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde) ... FAIL
test_plus_is_minus_backward_local (test.torch_test.TestChainTensor) ... ERROR
test_plus_is_minus_backward_remote (test.torch_test.TestChainTensor) ... ERROR
test_plus_is_minus_tensor_local (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_tensor_remote (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_variable_local (test.torch_test.TestChainTensor) ... ERROR
test_plus_is_minus_variable_remote (test.torch_test.TestChainTensor) ... ERROR
test_gpc_add (test.torch_test.TestGPCTensor) ... ok
test_gpc_unwrapped_add (test.torch_test.TestGPCTensor) ... ok
test_mpc_mul (test.torch_test.TestMPCTensor) ... ok
test_mpc_sum (test.torch_test.TestMPCTensor) ... ok
test___repr__ (test.torch_test.TestTorchTensor) ... ok
test_add_remote_tensor (test.torch_test.TestTorchTensor) ... ok
test_chain_send_get_tensor (test.torch_test.TestTorchTensor) ... ok
test_local_tensor_binary_methods (test.torch_test.TestTorchTensor)
Unit tests for methods mentioned on issue 1385 ... ok
test_local_tensor_iterable_methods (test.torch_test.TestTorchTensor) ... ok
test_local_tensor_tertiary_methods (test.torch_test.TestTorchTensor) ... ok
test_local_tensor_unary_methods (test.torch_test.TestTorchTensor)
Unit tests for methods mentioned on issue 1385 ... ok
test_multiple_pointers_to_same_target (test.torch_test.TestTorchTensor) ... FAIL
****
ERROR: test_plus_is_minus_backward_local (test.torch_test.TestChainTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/test/torch_test.py", line 172, in test_plus_is_minus_backward_local
    x = sy._PlusIsMinusTensor().on(x)
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 281, in on
    wrapper.init_grad_()
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 1346, in init_grad_
    self.grad.native_set_()
  File "/Users/llealhernandez/anaconda/envs/dlnd/lib/python3.6/site-packages/torch/autograd/variable.py", line 65, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'native_set_'

======================================================================
ERROR: test_plus_is_minus_backward_remote (test.torch_test.TestChainTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/test/torch_test.py", line 184, in test_plus_is_minus_backward_remote
    x = sy._PlusIsMinusTensor().on(x)
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 281, in on
    wrapper.init_grad_()
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 1346, in init_grad_
    self.grad.native_set_()
  File "/Users/llealhernandez/anaconda/envs/dlnd/lib/python3.6/site-packages/torch/autograd/variable.py", line 65, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'native_set_'
**************************************

**Comment by iamtrask** [comment]
Hi @llealgt! What version of python and pytorch are you using?

**Comment by iamtrask** [comment]
Interestingly - both of those errors likely mean that the test was run _before_ pytorch was hooked... as .native_set_ is a method we create. That's very strange indeed.

**Comment by iamtrask** [comment]
Even more strangely - i have unit tests which are failing but when i run them separately they work fine. I think this might involve us not creating our global variables correctly - such that some tests are getting run before the global variables are initialied.

**Comment by iamtrask** [comment]
Hey @llealgt - i think i fixed it... try pulling from master and see how it goes

**Comment by llealgt** [comment]
Still getting failed tests after  pulling from master ,here's some sample errors:

test_send_and_get_tensor (test.tensor_serde_test.TestTensorPointerSerde) ... FAIL
test_tensor2registered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde) ... FAIL
test_tensor2unregsitered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde) ... FAIL
setup module
WARNING:root:Torch was already hooked... skipping hooking process
test_plus_is_minus_backward_local (test.torch_test.TestChainTensor) ... ERROR
test_plus_is_minus_backward_remote (test.torch_test.TestChainTensor) ... ERROR
test_plus_is_minus_tensor_local (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_tensor_remote (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_variable_local (test.torch_test.TestChainTensor) ... ERROR
test_plus_is_minus_variable_remote (test.torch_test.TestChainTensor) ... ERROR
#############

ERROR: test_plus_is_minus_backward_local (test.torch_test.TestChainTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/test/torch_test.py", line 187, in test_plus_is_minus_backward_local
    x = sy._PlusIsMinusTensor().on(x)
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 281, in on
    wrapper.init_grad_()
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 1559, in init_grad_
    self.grad.native_set_()
  File "/Users/llealhernandez/anaconda/envs/dlnd/lib/python3.6/site-packages/torch/autograd/variable.py", line 65, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'native_set_'

======================================================================
ERROR: test_plus_is_minus_backward_remote (test.torch_test.TestChainTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/test/torch_test.py", line 199, in test_plus_is_minus_backward_remote
    x = sy._PlusIsMinusTensor().on(x)
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 281, in on
    wrapper.init_grad_()
  File "/Users/llealhernandez/Documents/Personal/Programming/PySyft/syft/core/frameworks/torch/tensor.py", line 1559, in init_grad_
    self.grad.native_set_()
  File "/Users/llealhernandez/anaconda/envs/dlnd/lib/python3.6/site-packages/torch/autograd/variable.py", line 65, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'native_set_'

**My conda env list of packages and versions**
(obtained using conda list)
alabaster                 0.7.11                    <pip>
appnope                   0.1.0                    py36_0  
aspy.yaml                 1.1.1                     <pip>
atomicwrites              1.2.1                    py36_0    anaconda
attrs                     18.2.0           py36h28b3542_0    anaconda
Babel                     2.6.0                     <pip>
blas                      1.0                         mkl    anaconda
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_0  
cached-property           1.5.1                     <pip>
certifi                   2018.8.24                py36_1    anaconda
cffi                      1.10.0                   py36_0  
cfgv                      1.1.0                     <pip>
cycler                    0.10.0                   py36_0  
decorator                 4.0.11                   py36_0  
docutils                  0.14                      <pip>
entrypoints               0.2.2                    py36_1  
freetype                  2.8                  h12048fb_1    anaconda
h5py                      2.8.0            py36h878fce3_3    anaconda
hdf5                      1.10.2               hfa1e0ec_1    anaconda
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
identify                  1.1.6                     <pip>
imagesize                 1.1.0                     <pip>
intel-openmp              2019.0                      118    anaconda
ipykernel                 4.6.0                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
jbig                      2.1                           0  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
keras                     1.0.7                    py36_0    conda-forge
kiwisolver                1.0.1            py36h792292d_0    anaconda
libcxx                    4.0.1                h579ed51_0    anaconda
libcxxabi                 4.0.1                hebd6815_0    anaconda
libgfortran               3.0.1                h93005f0_2    anaconda
libgpuarray               0.7.6                h1de35cc_0    anaconda
libpng                    1.6.34               he12f830_0    anaconda
libprotobuf               3.6.0                hd9629dc_0    anaconda
libtiff                   4.0.9                hcb84e12_2    anaconda
mako                      1.0.7                    py36_0    conda-forge
markupsafe                0.23                     py36_2  
matplotlib                2.2.2            py36ha7267d0_0    anaconda
mistune                   0.7.4                    py36_0  
mkl                       2019.0                      118    anaconda
mkl_fft                   1.0.4            py36h5d10147_1    anaconda
mkl_random                1.0.1            py36h5d10147_1    anaconda
mock                      2.0.0                    py36_0    conda-forge
more-itertools            4.3.0                    py36_0    anaconda
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
nodeenv                   1.3.2                     <pip>
notebook                  5.0.0                    py36_0  
numpy                     1.15.1           py36h6a91979_0    anaconda
numpy-base                1.15.1           py36h8a80b8c_0    anaconda
olefile                   0.44                     py36_0  
openssl                   1.0.2k                        1  
packaging                 17.1                      <pip>
pandas                    0.23.4           py36h6440ff4_0    anaconda
pandocfilters             1.4.1                    py36_0  
path.py                   10.1                     py36_0  
pbr                       3.1.1                    py36_0    conda-forge
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.2.1            py36h0263179_0    anaconda
pip                       9.0.1                    py36_1  
pluggy                    0.7.1            py36h28b3542_0    anaconda
pre-commit                1.11.0                    <pip>
prompt_toolkit            1.0.14                   py36_0  
protobuf                  3.6.0            py36h0a44026_0    anaconda
protobuf                  3.3.0                     <pip>
ptyprocess                0.5.1                    py36_0  
py                        1.6.0                    py36_0    anaconda
pycparser                 2.18                     py36_0  
pygments                  2.2.0                    py36_0  
pygpu                     0.7.6            py36h917ab60_0    anaconda
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytest                    3.8.0                    py36_0    anaconda
python                    3.6.1                         0  
python-dateutil           2.6.0                    py36_0  
pytorch                   0.2.0                py36_4cu75    soumith
pytz                      2017.2                   py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         0  
qtconsole                 4.3.0                    py36_0  
readline                  6.2                           2  
requests                  2.13.0                   py36_0  
scikit-learn              0.19.1           py36hffbff8c_0    anaconda
scipy                     1.1.0            py36h28f7352_1    anaconda
setuptools                40.2.0                   py36_0    anaconda
simplegeneric             0.8.1                    py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                     <pip>
Sphinx                    1.8.0                     <pip>
sphinx-rtd-theme          0.4.1                     <pip>
sphinxcontrib-websupport  1.1.0                     <pip>
sqlite                    3.13.0                        0  
tensorflow                1.1.0                    py36_0    conda-forge
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
theano                    0.9.0                    py36_1    conda-forge
tk                        8.5.18                        0  
toml                      0.9.6                     <pip>
tornado                   4.4.2                    py36_0  
tqdm                      4.11.2                    <pip>
traitlets                 4.3.2                    py36_0  
virtualenv                16.0.0                    <pip>
wcwidth                   0.1.7                    py36_0  
websockets                6.0                       <pip>
Werkzeug                  0.12.1                    <pip>
werkzeug                  0.12.2                   py36_0    conda-forge
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
xz                        5.2.4                h1de35cc_4    anaconda
yaml                      0.1.6                         0  
zlib                      1.2.11               hf3cbc9b_2    anaconda

**Comment by iamtrask** [comment]
your pytorch version is too old. You have 0.2.0 but you need 0.3.1

**Comment by iamtrask** [comment]
Hmmmmm....  this is the kind of error i thought i fixed... can you pull from master again and check?

**Comment by llealgt** [comment]
Nope, i created a new conda env, installed from scratch again and still getting failures:

ERROR: test_plus_is_minus_backward_local (test.torch_test.TestChainTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/luis/media/PySyft/test/torch_test.py", line 175, in test_plus_is_minus_backward_local
    z.backward()
  File "/media/luis/media/PySyft/syft/core/frameworks/torch/hook.py", line 423, in _execute_method_call
    return worker._execute_call(attr, self, *args, **kwargs)
  File "/media/luis/media/PySyft/syft/core/workers/base.py", line 891, in _execute_call
    result = child_type.handle_call(syft_command, owner=self)
  File "/media/luis/media/PySyft/syft/core/frameworks/torch/tensor.py", line 117, in handle_call
    result = child_type.handle_call(next_command, owner)
  File "/media/luis/media/PySyft/syft/core/frameworks/torch/tensor.py", line 404, in handle_call
    response = command(*args, **kwargs)
  File "/media/luis/media/PySyft/syft/core/frameworks/torch/hook.py", line 502, in new_backward
    self.native_native_backward(*args, **kwargs)
  File "/home/luis/anaconda2/envs/PySyft/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/luis/anaconda2/envs/PySyft/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: std::bad_alloc

======================================================================
FAIL: test_send_and_get_tensor (test.tensor_serde_test.TestTensorPointerSerde)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/luis/media/PySyft/test/tensor_serde_test.py", line 228, in test_send_and_get_tensor
    assert xid in me._objects
AssertionError

======================================================================
FAIL: test_tensor2registered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/luis/media/PySyft/test/tensor_serde_test.py", line 182, in test_tensor2registered_pointer2tensor
    assert x.id in me._objects
AssertionError

======================================================================
FAIL: test_tensor2unregsitered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/luis/media/PySyft/test/tensor_serde_test.py", line 145, in test_tensor2unregsitered_pointer2tensor
    assert x.id in me._objects
AssertionError

======================================================================
FAIL: test_multiple_pointers_to_same_target (test.torch_test.TestTorchTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/luis/media/PySyft/test/torch_test.py", line 277, in test_multiple_pointers_to_same_target
    assert False
AssertionError

======================================================================
FAIL: test_send_get_tensor (test.torch_test.TestTorchTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/luis/media/PySyft/test/torch_test.py", line 235, in test_send_get_tensor
    assert x_id in me._objects
AssertionError

----------------------------------------------------------------------

**Comment by llealgt** [comment]
I just made a pull from master and all tests are passing now
