### ISSUE TITLE
spdz_mul() - TypeError: can only concatenate list (not "dict_values") to list

### ISSUE THREAD

**Issue by mkucz95** [OpenMined/PySyft#2494]
Error in `spdz_mul()` [Line 44](https://github.com/OpenMined/PySyft/blob/2e5af85043a29d5122243761e2e2d7cf2a5cb952/syft/frameworks/torch/crypto/spdz.py#L44) when concatenating list with dictionary values:

When the number of workers is greater than 2 I get the error:
`TypeError: can only concatenate list (not "dict_values") to list `

![image](https://user-images.githubusercontent.com/8993371/62837450-4ee53700-bc24-11e9-9b1d-a04fad18c5c8.png)

To me it seems like [line 44](https://github.com/OpenMined/PySyft/blob/2e5af85043a29d5122243761e2e2d7cf2a5cb952/syft/frameworks/torch/crypto/spdz.py#L44) should be:

`j = sy.MultiPointerTensor(children=[j1] + list(j0.child.values()))`

I haven't been working with PySyft for very long so please let me know if I am missing something!

**Comment by sanvenDev** [comment]
Can anyone fix this to the original PySyft Code? I'm also facing same issue, when workers are greater than 2.

**Comment by mkucz95** [comment]
I started looking into this, but it looks like most or all the functions in securenn.py only allow for two workers (alice, bob to be specific). Since I am relatively new to PySyft it's starting to look a little more intense than just changing the syntax to what I suggested earlier.

**Comment by LaRiffle** [comment]
Apparently it has been fixed :)

**Comment by sandeepwww** [comment]
I am still seeing the same issue. I even tried making changes according to commit in the thread, still seeing the same error.

![image](https://user-images.githubusercontent.com/8968772/71577789-8e50e900-2b1b-11ea-993e-5d022fed38a8.png)
