### ISSUE TITLE
AdditiveSharingTensor changes 'garbage_collect_data' while simplifying

### ISSUE THREAD

**Issue by sukhadj** [OpenMined/PySyft#2882]
**Describe the bug**
AdditiveSharingTensor changes the value of garbage_collect_data while serialization. This results in inconsitent serialization for high level tensors (AutogradTensor wrapped around AdditiveSharingTensor, etc)

**To Reproduce**
```python
x = th.tensor([1, 2, 3])
x_share = x.share(alice, bob, requires_grad=True)
print(x_share.child.child.child["alice"].garbage_collect_data)
x_sh_sh = x_share.send(sj)
print(x_share.child.child.child["alice"].garbage_collect_data)

```
Outputs:
```python
True
False
```
**Additional context**
It gets changed [here](
https://github.com/OpenMined/PySyft/blob/a35542ab518ea1b014e37d44060a5b3a8c19a211/syft/frameworks/torch/tensors/interpreters/additive_shared.py#L993).
  
How should we deal with this? :thinking:

**Comment by karlhigley** [comment]
Serialization/deserialization itself should never change the state or type of an object, so...it seems like we might need a mechanism for making changes before sending and/or after receiving. There's a similar issue with `PointerTensor`, where deserialization can return either a `PointerTensor` or a `torch.Tensor`, because the deserialization checks to see if the tensor is local and loads it if so.

**Comment by karlhigley** [comment]
@iamtrask @vvmnnnkv Thoughts on this? Could we introduce some kind of hook methods for making changes before sending or after receiving?

**Comment by LaRiffle** [comment]
I would be tempted here by a dirty fix

```python
tensor.set_garbage_collect_data(False)

r = (
            sy.serde.msgpack.serde._simplify(worker, tensor.id),
            tensor.field,
            sy.serde.msgpack.serde._simplify(worker, tensor.crypto_provider.id),
            chain,
        )
tensor.set_garbage_collect_data(True)
return r
```

(But this doesn't concern the PointerTensor issue you mentioned @karlhigley 
This phenomenon is due to how Plans are implemented, because they store serialized pointers which needs to deserialize as tensors. It's dirty, it my fault lol, and maybe changing the way Plans are created is the best idea to get rid of this improper deserialization behavior)

**Comment by karlhigley** [comment]
I'm fine with a dirty fix for now to make `grad_fn` serialization work and get it merged. I do think these issues are related though, in that they're both cases where another kind of operation is entangled with serialization/deserialization. Thinking that might be a sign that there's a missing abstraction here that would provide common structure for operations that need to happen around sending/receiving.

**Comment by vvmnnnkv** [comment]
> I would be tempted here by a dirty fix

Shouldn't it be `tensor.set_garbage_collect_data(<previous value>)`? :-)
Or is it always True?

**Comment by sukhadj** [comment]
Hey, I have updated the code in #2871  with dirty fix suggested by @LaRiffle. 

> > I would be tempted here by a dirty fix
> 
> Shouldn't it be `tensor.set_garbage_collect_data(<previous value>)`? :-)
> Or is it always True?

It is now set to previous value.

**Comment by gmuraru** [comment]
@sukhadj I think we can close this since it is solved by #2871. Right?

**Comment by sukhadj** [comment]
@gmuraru No it doesn't fix the issue. The dirty fix itself generates some more issues. Hence changed the test cases according to previous setting  ☺️.
